title: メゾンひな
url: https://maison-hina.com
baseurl: ""
markdown: kramdown
defaults:
  - scope:
      path: "en"
    values:
      lang: en
      layout: default
  - scope:
      path: "ja"
    values:
      lang: ja
      layout: default
